### ISSUE TITLE
json报错

### ISSUE THREAD

**Issue by MikasaEureka** [xiao-niu-ren/BUPT_nCoV_Auto_Clock_in#1]
是cookies更新的问题吗

**Comment by xiao-niu-ren** [comment]
现在好像可以了，环境变量里的AREA的值要用+号隔开  比如 北京市+海淀区

**Comment by MikasaEureka** [comment]
有没有机会加一个server酱的微信推送

**Comment by MikasaEureka** [comment]
https://github.com/MikasaEureka/BUPT_nCoV_easily_fixed_form
我弄了一个带server酱的

**Comment by xiao-niu-ren** [comment]
好嘞

**Comment by MikasaEureka** [comment]
对了，你的area为啥要加+啊

**Comment by xiao-niu-ren** [comment]
抓了一下包，好像是用空格隔开的，不是+，改回去了= =

**Comment by MikasaEureka** [comment]
time有bug，我刚运行了一次，打开时间是utc的，没加上8小时，所以打卡时间是昨天

**Comment by MikasaEureka** [comment]
不懂，，，我刚才看oldinfo里的date是0403，下次试试0点以后再说

**Comment by MikasaEureka** [comment]
昨晚糊涂了，应该是UTC16点以前用actions进行操作才是同一天的日期
